### ISSUE TITLE
[Overview] Frontend Requirements (wip)

### ISSUE THREAD

**Issue by johannesliem** [acdh-oeaw/InTaVia-Backend#187]
# InTaVia Endpoints

A collection of issues regarding the InTaVia endpoints. Missing endpoints, required changes, etc. for finalizing the planned features of the frontend.

### Bugs

- [x] Stats in response not correct: https://github.com/InTaVia/InTaVia-Backend/issues/185
- [x] Not all pages return a "full" (=limit) array of results: https://github.com/InTaVia/InTaVia-Backend/issues/186

### Response shape

- [x] simplify linked ids: https://github.com/InTaVia/InTaVia-Backend/issues/166
- [ ] what is source.citation: https://github.com/InTaVia/InTaVia-Backend/issues/15,
https://github.com/InTaVia/InTaVia-Backend/issues/173 
- [ ] `type` attribute for `Place` (but also for `CHO` and `Group`) entities:
https://github.com/InTaVia/InTaVia-Backend/issues/16
- [ ] occupations (and gender) as array of vocabulary ids:
https://github.com/InTaVia/InTaVia-Backend/issues/131
- [ ] gender: https://github.com/InTaVia/InTaVia-Backend/issues/17

### Query parameters

- [ ] gender should accept array: https://github.com/InTaVia/InTaVia-Backend/issues/55

## Statistical Endpoints
Required for Visual Querying (VQ) and Visual Summaries of search results

- [x] entity types count
- [ ] #199
- [ ] #201

- [ ] occupation
- [ ] #200
- [ ] #198

### Event-kind

- [ ] honour event: https://github.com/InTaVia/InTaVia-Backend/issues/164
- [ ] period event: https://github.com/InTaVia/InTaVia-Backend/issues/55
